CRM/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^rbac/', include(('rbac.urls','rbac'),namespace='rbac')),
    url(r'^', include('web.urls')),
]

rbac/service/urls.py
from django.urls import reverse
from django.http import QueryDict

def memory_url(request, name, *args, **kwargs):
    """
    生成带有原搜索条件的URL（替代了模板中的url）
    :param request:
    :param name:
    :return:
    """
    basic_url = reverse(name, args=args, kwargs=kwargs)

    # 当前URL中无参数
    if not request.GET:
        return basic_url

    query_dict = QueryDict(mutable=True)
    query_dict['_filter'] = request.GET.urlencode()  # mid=2&age=99

    return "%s?%s" % (basic_url, query_dict.urlencode())


def memory_reverse(request, name, *args, **kwargs):
    """
    反向生成URL
        http://127.0.0.1:8001/rbac/menu/add/?_filter=mid%3D2
        1. 在url中讲原来搜索条件，如filter后的值
        2. reverse生成原来的URL，如：/menu/list/
        3. /menu/list/?mid%3D2

    示例：
    :param request:
    :param name:
    :param args:
    :param kwargs:
    :return:
    """
    url = reverse(name, args=args, kwargs=kwargs)
    origin_params = request.GET.get('_filter')
    if origin_params:
        url = "%s?%s" % (url, origin_params,)

    return url

rbac/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include
from rbac.views import role,user,menu

urlpatterns = [
    url(r'^role/list/$',role.role_list,name='role_list'),
    url(r'^role/add/$',role.role_add,name='role_add'),
    url(r'^role/edit/(?P<pk>\d+)/$',role.role_edit,name='role_edit'),
    url(r'^role/del/(?P<pk>\d+)/$',role.role_del,name='role_del'),

    url(r'^user/list/$',user.user_list,name='user_list'),
    url(r'^user/add/$',user.user_add,name='user_add'),
    url(r'^user/edit/(?P<pk>\d+)/$',user.user_edit,name='user_edit'),
    url(r'^user/del/(?P<pk>\d+)/$',user.user_del,name='user_del'),
    url(r'^user/ResetPassword/(?P<pk>\d+)/$',user.user_ResetPassword,name='user_ResetPassword'),

    url(r'^menu/list/$',menu.menu_list,name='menu_list'),
    url(r'^menu/add/$',menu.menu_add,name='menu_add'),
    url(r'^menu/edit/(?P<pk>\d+)/$',menu.menu_edit,name='menu_edit'),
    url(r'^menu/del/(?P<pk>\d+)/$',menu.menu_del,name='menu_del'),
]

rbac/models.py
from django.db import models


class Menu(models.Model):
    title = models.CharField(verbose_name='菜单', max_length=32)
    icon = models.CharField(verbose_name='图标', max_length=32)

    def __str__(self):
        return self.title

class Permission(models.Model):
    """
    权限表
    """
    title = models.CharField(verbose_name='标题', max_length=32)
    url = models.CharField(verbose_name='含正则的URL', max_length=128)

    pid = models.ForeignKey(verbose_name='关联的权限',to='Permission',blank=True,null=True,help_text='用户选择二级菜单',
                               related_name='parents',on_delete=models.CASCADE)

    name = models.CharField(verbose_name='URL',unique=True,max_length=32)

    # is_menu = models.BooleanField(verbose_name='make a list',default=False)
    # icon = models.CharField(verbose_name='icon',max_length=32,null=True,blank=True) #表示可以为空

    menu = models.ForeignKey(verbose_name='菜单',to='Menu',blank=True,null=True,help_text='null表示非菜单',on_delete=models.CASCADE)

    def __str__(self):
        return self.title


class Role(models.Model):
    """
    角色
    """
    title = models.CharField(verbose_name='角色名称', max_length=32)
    permission = models.ManyToManyField(verbose_name='拥有的所有权限', to='Permission', blank=True)

    def __str__(self):
        return self.title


class UserInfo(models.Model):
    """
    用户表
    """
    name = models.CharField(verbose_name='用户名', max_length=32)
    password = models.CharField(verbose_name='密码', max_length=64)
    email = models.CharField(verbose_name='邮箱', max_length=32)
    role = models.ManyToManyField(verbose_name='拥有的所有角色', to='Role', blank=True)

    def __str__(self):
        return self.name

rbac/forms/menu.py
from django import forms
from rbac import models

class MenuModelForm(forms.ModelForm):
    class Meta:
        model = models.Menu
        fields = ['title','icon']
        widgets = {
            'title':forms.TextInput(attrs={'class':'form-control'}),
            'icon':forms.RadioSelect(
                choices=[
                    ['x1','xxx1'],
                    ['x2','xxx2']
                ]
            )
        }

rbac/forms/role.py
from rbac import models
from django import forms


class RoleModeForm(forms.ModelForm):
    class Meta:
        model = models.Role
        fields = ['title']
        widgets = {
            'title' : forms.TextInput(attrs={'class':'form-control'})
        }

rbac/forms/user.py
from rbac import models
from django import forms
from django.core.exceptions import ValidationError

class UserModeForm(forms.ModelForm):
    confirm_password = forms.CharField(label='确认密码')
    class Meta:
        model = models.UserInfo
        fields = ['name','email','password','confirm_password']

        # error_messages = {'name'}     手动设置错误信息

    def __init__(self,*args,**kwargs):
        super(UserModeForm, self).__init__(*args,**kwargs)

        for name,field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'

    def clean_confirm_password(self):
        '''
        检测密码是否一致
        :return:
        '''
        password = self.cleaned_data['password']
        confirm_password = self.cleaned_data['confirm_password']

        if password != confirm_password:
            raise ValidationError('两次密码不一致！')

        return confirm_password

class UpdateUserModeForm(forms.ModelForm):
    class Meta:
        model = models.UserInfo
        fields = ['name','email']

    def __init__(self,*args,**kwargs):
        super(UpdateUserModeForm, self).__init__(*args,**kwargs)

        for name,field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'

class ResetPasswordUserModeForm(forms.ModelForm):
    confirm_password = forms.CharField(label='确认密码')
    class Meta:
        model = models.UserInfo
        fields = ['password','confirm_password']

    def __init__(self,*args,**kwargs):
        super(ResetPasswordUserModeForm, self).__init__(*args,**kwargs)

        for name,field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'

    def clean_confirm_password(self):           # 设置钩子检测两个密码是否一致
        '''
        检测密码是否一致
        :return:
        '''
        password = self.cleaned_data['password']
        confirm_password = self.cleaned_data['confirm_password']

        if password != confirm_password:
            raise ValidationError('两次密码不一致！')

        return confirm_password

rbac/views/menu.py
from django.shortcuts import render,HttpResponse,redirect,reverse
from rbac import models
from rbac.forms.menu import MenuModelForm
from rbac.service.urls import memory_reverse

def menu_list(request):
    '''
    菜单和权限列表
    :param request:
    :return:
    '''

    menus = models.Menu.objects.all()

    menu_id =request.GET.get('mid')
    print('menu_id:',menu_id)

    return render(
        request,
        'rbac/menu_list.html',
        {
            'menus':menus,
            'menu_id':menu_id,
        }
    )

def menu_add(request):
    """
    添加一级菜单
    :param request:
    :return:
    """
    if request.method == 'GET':
        form = MenuModelForm()
        return render(request, 'rbac/change.html', {'form': form})

    form = MenuModelForm(data=request.POST)
    if form.is_valid():
        form.save()
        return redirect(memory_reverse(request, 'rbac:menu_list'))

    return render(request, 'rbac/change.html', {'form': form})

def menu_edit(request, pk):
    """

    :param request:
    :param pk:
    :return:
    """
    obj = models.Menu.objects.filter(id=pk).first()
    if not obj:
        return HttpResponse('菜单不存在')
    if request.method == 'GET':
        form = MenuModelForm(instance=obj)
        return render(request, 'rbac/change.html', {'form': form})

    form = MenuModelForm(instance=obj, data=request.POST)
    if form.is_valid():
        form.save()
        return redirect(memory_reverse(request, 'rbac:menu_list'))

    return render(request, 'rbac/change.html', {'form': form})

def menu_del(request, pk):
    """

    :param request:
    :param pk:
    :return:
    """
    url = memory_reverse(request, 'rbac:menu_list')
    if request.method == 'GET':
        return render(request, 'rbac/delete.html', {'cancel': url})

    models.Menu.objects.filter(id=pk).delete()
    return redirect(url)

rbac/views/role.py
from django.shortcuts import render,HttpResponse,redirect,reverse
from rbac.forms.role import RoleModeForm
from rbac import models



def role_list(request):
    role_queryset = models.Role.objects.all()

    return render(request,'rbac/role_list.html',{'roles':role_queryset})


def role_add(request):
    '''
    添加角色
    :param request:
    :return:
    '''
    if request.method == 'GET':
        form = RoleModeForm()
        return render(request,'rbac/change.html',{'form':form})

    form = RoleModeForm(data = request.POST)
    if form.is_valid():
        form.save()
        return redirect(reverse('rbac:role_list'))

    return render(request, 'rbac/change.html', {'form': form})

def role_edit(request,pk):
    obj = models.Role.objects.filter(id=pk).first()
    if not obj:
        return HttpResponse('角色不存在')

    if request.method == 'GET':
        form = RoleModeForm(instance=obj)
        return render(request,'rbac/change.html',{'form':form})

    form = RoleModeForm(instance=obj,data = request.POST)
    if form.is_valid():
        form.save()
        return redirect(reverse('rbac:role_list'))

    return render(request,'rbac/change.html',{'form':form})

def role_del(request,pk):
    """
    删除角色
    :param request:
    :param pk:
    :return:
    """
    origin_url = reverse('rbac:role_list')     #反向生成URL

    if request.method == 'GET':
        return  render(request,'rbac/delete.html',{'cancel':origin_url})

    models.Role.objects.filter(id=pk).delete()
    return redirect(origin_url)

rbac/views/user.py
from django.shortcuts import render,HttpResponse,redirect,reverse
from rbac.forms.user import UserModeForm,UpdateUserModeForm,ResetPasswordUserModeForm
from rbac import models


def user_list(request):
    """
    角色列表
    :param request:
    :return:
    """

    user_queryset = models.UserInfo.objects.all()
    return render(request,'rbac/user_list.html',{'users':user_queryset})


def user_add(request):
    '''
    添加角色
    :param request:
    :return:
    '''
    if request.method == 'GET':
        form = UserModeForm()
        return render(request,'rbac/change.html',{'form':form})

    form = UserModeForm(data = request.POST)
    if form.is_valid():
        form.save()
        return redirect(reverse('rbac:user_list'))

    return render(request, 'rbac/change.html', {'form': form})

def user_edit(request,pk):
    obj = models.UserInfo.objects.filter(id=pk).first()
    if not obj:
        return HttpResponse('角色不存在')

    if request.method == 'GET':
        form = UpdateUserModeForm(instance=obj)
        return render(request,'rbac/change.html',{'form':form})

    form = UpdateUserModeForm(instance=obj,data = request.POST)
    if form.is_valid():
        form.save()
        return redirect(reverse('rbac:user_list'))

    return render(request,'rbac/change.html',{'form':form})

def user_del(request,pk):
    """
    删除角色
    :param request:
    :param pk:
    :return:
    """
    origin_url = reverse('rbac:user_list')     #反向生成URL

    if request.method == 'GET':
        return  render(request,'rbac/delete.html',{'cancel':origin_url})

    models.UserInfo.objects.filter(id=pk).delete()
    return redirect(origin_url)


def user_ResetPassword(request,pk):
    obj = models.UserInfo.objects.filter(id=pk).first()

    if request.method == 'GET':
        form = ResetPasswordUserModeForm()
        return render(request,'rbac/change.html',{'form':form})

    form = ResetPasswordUserModeForm(instance=obj,data = request.POST)
    if form.is_valid():
        form.save()
        return redirect(reverse('rbac:user_list'))

    return render(request,'rbac/change.html',{'form':form})

rbac/templates/rbac/breadcrumb.html
 <div>
    <ol class="breadcrumb no-radius no-margin" style="border-bottom: 1px solid #ddd;">
        {% for item in record_list %}
            {% if item.class %}
                <li class="{{ item.class }}">{{ item.title }}</li>
            {% else %}
                <li><a href="{{ item.url}}">{{ item.title }}</a></li>
            {% endif %}
        {% endfor %}
    </ol>
</div>

rbac/templates/rbac/change.html
{% extends 'layout.html' %}
{% block content %}
    <div class="luffy-container">
        <form class="form-horizontal" method="post" novalidate>
            {% csrf_token %}
            {% for field in form %}
                <div class="form-group">
                    <label class="col-sm-2 control-label">{{ field.label }}</label>
                    <div class="col-sm-8">
                        {{ field }}
                        <span style="color: red;">{{ field.errors.0 }}</span>
                    </div>
                </div>
            {% endfor %}
            <div class="form-group">
                <div class="col-sm-offset-2 col-sm-8">
                    <input type="submit" value="保 存" class="btn btn-primary">
                </div>
            </div>
        </form>
    </div>

{% endblock %}

rbac/templates/rbac/delete.html
{% extends 'layout.html' %}

{% block content %}
    <div class="luffy-container">
        <div class="alert alert-danger" role="alert">
            <form method="post">
                {% csrf_token %}
                <p style="font-size: 13px;"><i class="fa fa-warning" aria-hidden="true"></i> 删除后将不可恢复，请确定是否删除？</p>


                <div style="margin-top: 20px;">
                    <a href="{{ cancel }}" class="btn btn-default btn-sm">取消</a>

                    <input type="submit" class="btn btn-danger btn-sm" value="确 认">
                </div>
            </form>
        </div>
    </div>

{% endblock %}

rbac/templates/rbac/menu_list.html
{% extends 'layout.html' %}
{% load rbac %}
{% block css %}
    <style>
        tr.active {
            border-left: 13px solid #ac2925;
        }
    </style>

{% endblock %}



{% block content %}
    <div class="luffy-container">

        <div class="col-md-3">

            <div class="panel panel-default">
                <!-- Default panel contents -->
                <div class="panel-heading">
                    <i class="fa fa-book" aria-hidden="true"></i> 一级菜单
                    <a href="{% memory_url request 'rbac:menu_add' %}" class="right btn btn-success btn-xs"
{#                       {% memory_url request 'rbac:menu_add' %}#}
                       style="padding: 2px 8px;margin: -3px;">
                        <i class="fa fa-plus-circle" aria-hidden="true"></i>
                        新建
                    </a>


                </div>

                <!-- Table -->
                <table class="table">
                    <thead>
                    <tr>
                        <th>名称</th>
                        <th>图标</th>
                        <th>选项</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for row in menus %}
                        <tr class="{% if row.id|safe == menu_id %}active{% endif %}">
                            <td>
                                <a href="?mid={{ row.id }}">{{ row.title }}</a>
                            </td>
                            <td>
                                <i class="fa {{ row.icon }}" aria-hidden="true"></i>
                            </td>
                            <td>
                                <a style="color: #333333;" href="{% memory_url request 'rbac:menu_edit' pk=row.id %}">
                                    <i class="fa fa-edit" aria-hidden="true"></i></a>


                                <a style="color: #d9534f;" href="{% memory_url request 'rbac:menu_del' pk=row.id %}"><i
                                        class="fa fa-trash-o"></i></a>

                            </td>
                        </tr>
                    {% endfor %}

                    </tbody>
                </table>
            </div>

        </div>
    </div>

{% endblock %}

rbac/templates/rbac/multi_menu.html
<div class="multi-menu">
    {% for item in menu_dict.values %}
        <div class="item">
            <div class="title"><span class="icon-wrap"><i class="fa {{ item.icon }}"></i></span> {{ item.title }}</div>
            <div class="body {{ item.class }}">
                {% for per in item.children %}
                    <a class="{{ per.class }}" href="{{ per.url }}">{{ per.title }}</a>
                {% endfor %}
            </div>
        </div>
    {% endfor %}
</div>

rbac/templates/rbac/role_list.html
{% extends 'layout.html' %}
{% block content %}

    <div class="luffy-container">
        <div class="btn-group" style="margin: 5px 0">
                <a class="btn btn-default" href={% url 'rbac:role_add' %}>
                <i class="fa fa-plus-square" aria-hidden="true"></i> 添加角色
                </a>
        </div>

        <table class="table table-bordered table-hover">
            <thead>
            <tr>
                <th>ID</th>
                <th>名称</th>
                <th>选项</th>
            </tr>
            </thead>
            <tbody>
            {% for row in roles %}
                <tr>
                    <td>{{ row.id }}</td>
                    <td>{{ row.title }}</td>
                    <td>
                        <a style="color:#333333" href="{% url 'rbac:role_edit' pk=row.id %}">
                            <i class="fa fa-edit" aria-hidden="true"></i>
                        </a>

                        <a style="color:#333333" href="{% url 'rbac:role_del' pk=row.id %}">
                            <i class="fa fa-trash-o"></i>
                        </a>

                    </td>


                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>

{% endblock %}

rbac/templates/rbac/static_menu.html
<div class="static-menu">
    {% for item in menu_list %}
            <a href={{ item.url }}>
        <span class="icon-wrap"><i class="fa {{ item.icon }}"></i></span> {{ item.title }}</a>
    {% endfor %}
</div>

rbac/templates/rbac/test.html
{% load staticfiles %}
{% load rbac %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>路飞学城</title>
    <link rel="shortcut icon" href="{% static 'imgs/luffy-study-logo.png' %} ">
    <link rel="stylesheet" href="{% static 'plugins/bootstrap/css/bootstrap.css' %} "/>
    <link rel="stylesheet" href="{% static 'plugins/font-awesome/css/font-awesome.css' %} "/>
    <link rel="stylesheet" href="{% static 'css/commons.css' %} "/>
    <link rel="stylesheet" href="{% static 'css/nav.css' %} "/>
    <link rel="stylesheet" href="{% static 'rbac/css/rbac.css' %} "/>
    <style>
        body {
            margin: 0;
        }

        .no-radius {
            border-radius: 0;
        }

        .no-margin {
            margin: 0;
        }

        .pg-body > .left-menu {
            background-color: #EAEDF1;
            position: absolute;
            left: 1px;
            top: 48px;
            bottom: 0;
            width: 220px;
            border: 1px solid #EAEDF1;
            overflow: auto;
        }

        .pg-body > .right-body {
            position: absolute;
            left: 225px;
            right: 0;
            top: 48px;
            bottom: 0;
            overflow: scroll;
            border: 1px solid #ddd;
            border-top: 0;
            font-size: 13px;
            min-width: 755px;
        }

        .navbar-right {
            float: right !important;
            margin-right: -15px;
        }

        .luffy-container {
            padding: 15px;
        }


    </style>
</head>
<body>

<div class="pg-header">
    <div class="nav">
        <div class="logo-area left">
            <a href="#">
                <img class="logo" src="{% static 'imgs/logo.svg' %}">
                <span style="font-size: 18px;">路飞学城 </span>
            </a>
        </div>

        <div class="left-menu left">
            <a class="menu-item">资产管理</a>
            <a class="menu-item">用户信息</a>
            <a class="menu-item">路飞管理</a>
            <div class="menu-item">
                <span>使用说明</span>
                <i class="fa fa-caret-down" aria-hidden="true"></i>
                <div class="more-info">
                    <a href="#" class="more-item">管他什么菜单</a>
                    <a href="#" class="more-item">实在是编不了</a>
                </div>
            </div>
        </div>

        <div class="right-menu right clearfix">

            <div class="user-info right">
                <a href="#" class="avatar">
                    <img class="img-circle" src="{% static 'imgs/default.png' %}">
                </a>

                <div class="more-info">
                    <a href="#" class="more-item">个人信息</a>
                    <a href="#" class="more-item">注销</a>
                </div>
            </div>

            <a class="user-menu right">
                消息
                <i class="fa fa-commenting-o" aria-hidden="true"></i>
                <span class="badge bg-success">2</span>
            </a>

            <a class="user-menu right">
                通知
                <i class="fa fa-envelope-o" aria-hidden="true"></i>
                <span class="badge bg-success">2</span>
            </a>

            <a class="user-menu right">
                任务
                <i class="fa fa-bell-o" aria-hidden="true"></i>
                <span class="badge bg-danger">4</span>
            </a>
        </div>

    </div>
</div>
<div class="pg-body">
    <div class="left-menu">
        <div class="menu-body">
            {% multi_menu request %}
        </div>
    </div>
    <div class="right-body">
        <div>
            <ol class="breadcrumb no-radius no-margin" style="border-bottom: 1px solid #ddd;">

                <li><a href="#">首页</a></li>
                <li class="active">客户管理</li>

            </ol>
        </div>
        {% block content %} {% endblock %}
    </div>
</div>


<script src="{% static 'js/jquery-3.3.1.min.js' %} "></script>
<script src="{% static 'plugins/bootstrap/js/bootstrap.js' %} "></script>
<script src="{% static 'rbac/js/rbac.js' %} "></script>

{% block js %} {% endblock %}
</body>
</html>

rbac/templates/rbac/user_list.html
{% extends 'layout.html' %}
{% block content %}

    <div class="luffy-container">
        <div class="btn-group" style="margin: 5px 0">
                <a class="btn btn-default" href="{% url 'rbac:user_add' %}">
                <i class="fa fa-plus-square" aria-hidden="true"></i> 添加角色
                </a>
        </div>

        <table class="table table-bordered table-hover">
            <thead>
            <tr>
                <th>序号</th>
                <th>用户名</th>
                <th>邮箱</th>
                <th>重置密码</th>
                <th>操作</th>
            </tr>
            </thead>
            <tbody>
            {% for row in users %}
                <tr>
                    <td>{{ forloop.counter }}</td>
                    <td>{{ row.name }}</td>
                    <td>{{ row.email }}</td>
                    <td><a href="{% url 'rbac:user_ResetPassword' pk=row.id %}">重置密码</a></td>
                    <td>
                        <a style="color:#333333" href="{% url 'rbac:user_edit' pk=row.id %}">
                            <i class="fa fa-edit" aria-hidden="true"></i>
                        </a>

                        <a style="color:#333333" href="{% url 'rbac:user_del' pk=row.id %}">
                            <i class="fa fa-trash-o"></i>
                        </a>

                    </td>


                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>

{% endblock %}